# Generated by Django 3.2.5 on 2021-07-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id_candidates', models.AutoField(primary_key=True, serialize=False)),
                ('f_i_o', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('add_date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('review', models.CharField(max_length=255)),
                ('working_place', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id_tech', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id_link', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=255)),
                ('id_candidates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.candidates')),
                ('id_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.technologies')),
            ],
        ),
    ]
